### ISSUE TITLE
bot 回答在这里不会引用上下文的信息了

### ISSUE THREAD

**Issue by Laifang** [yuzd/maui_chatgpt#1]
![image](https://user-images.githubusercontent.com/20664974/208865566-a8ea432a-e318-4351-a8cf-528193bd46a2.png)
**### 而且经常回答一些我没有问过的问题，答非所问，是api key的问题 还是  程序设计的问题？**
![image](https://user-images.githubusercontent.com/20664974/208865659-8d288512-6ee5-4a21-9abc-75a795e40754.png)

**Comment by yuzd** [comment]
这个你研究下openapi文档，等我阳康了也看看
